name = "time"
lintDriver = "batteries/runLinter"
defaultTargets = ["Time"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.25.0"

[[lean_lib]]
name = "Time"
